name: demo
description: An example app showcasing the capabilities of Synk
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  synk: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
