name: synk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "packages/synk/**"
      - ".github/workflows/synk.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "packages/synk/**"
      - ".github/workflows/synk.yaml"
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: "**/*.md"
      modified_files_only: false

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: "3.11.0"
      working_directory: "packages/synk"
      setup: "ln -sf ../../.dart_tool .dart_tool"

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: "packages/synk"
